trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - template: .build/variables.yaml

stages:
  - stage: Build
    jobs:
      - job: build
        strategy:
          matrix:
            amd64:
              architecture: amd64

        steps:
          - template: .build/build-container.yaml

  - stage: Deploy
    jobs:
      - job: update_repository
        steps:
          - template: .build/push-to-repository.yaml